In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')


Mounted at /content/drive


In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [2]:
df = pd.read_csv('Titanic-Dataset.csv')

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [4]:
# Select required features
features = ['Pclass', 'Age', 'Fare']
target = 'Survived'

# Handle missing values
df['Age'].fillna(df['Age'].mean(), inplace=True)

X = df[features]
y = df[target]

# Normalize using Min-Max Scaling
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

print("Normalized Features:")
print(X_scaled[:5])

Normalized Features:
[[1.         0.27117366 0.01415106]
 [0.         0.4722292  0.13913574]
 [1.         0.32143755 0.01546857]
 [0.         0.43453129 0.1036443 ]
 [1.         0.43453129 0.01571255]]


C:\Users\Hello\AppData\Local\Temp\ipykernel_32536\4218020685.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)


In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

In [6]:
model = tf.keras.models.Sequential([

    tf.keras.layers.Dense(
        2,
        input_dim=3,
        activation='sigmoid'
    ),

    tf.keras.layers.Dense(
        1,
        activation='sigmoid'
    )

])

C:\Users\Hello\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [7]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [8]:
history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2
)

Epoch 1/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.3849 - loss: 0.7153 - val_accuracy: 0.3497 - val_loss: 0.7154
Epoch 2/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3919 - loss: 0.7023 - val_accuracy: 0.4126 - val_loss: 0.7013
Epoch 3/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4587 - loss: 0.6916 - val_accuracy: 0.5175 - val_loss: 0.6902
Epoch 4/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6292 - loss: 0.6832 - val_accuracy: 0.6853 - val_loss: 0.6800
Epoch 5/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6819 - loss: 0.6762 - val_accuracy: 0.6713 - val_loss: 0.6722
Epoch 6/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6749 - loss: 0.6709 - val_accuracy: 0.6573 - val_loss: 0.6658
Epoch 7/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6485 - loss: 0.6666 - val_accuracy: 0.6643 - val_loss: 0.6611
Epoch 8/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6309 - loss: 0.6632 - val_accuracy: 0.6503 - v

In [9]:
loss, accuracy = model.evaluate(X_test, y_test)

print("Accuracy:", accuracy)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7318 - loss: 0.5963 
Accuracy: 0.7318435907363892


In [11]:
model.save('titanic_ann_model.keras')

In [14]:
# from google.colab import files

# files.download('titanic_ann_model.keras')

In [16]:
import joblib

joblib.dump(scaler, 'scaler.pkl')

# files.download('scaler.pkl')

['scaler.pkl']